[package]
name = "matrix-hookshot"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
contrast = "0"
hex = "0.4.3"
imap = "2"
md-5 = "0.8.0"
napi = {version="2", features=["serde-json"]}
napi-derive = "2"
native-tls = "0.2.8"
rgb = "0"
serde = "1"
serde_derive = "1"
serde_json = "1"
url = "2"

[build-dependencies]
napi-build = "1"
