[package]
name = "matrix-hookshot"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = {version="2", features=["serde-json"]}
napi-derive = "2"
url = "2"
serde_json = "1"
serde = "1"
serde_derive = "1"
serde_yaml = "0"
contrast = "0"
rgb = "0"
md-5 = "0.8.0"
hex = "0.4.3"
indoc = "1.0"

[build-dependencies]
napi-build = "1"
