name: Newsfile

on:
  pull_request:
    branches: [ main ]
  merge_group:

jobs:
  changelog:
    runs-on: ubuntu-latest
    # No newsfile required for dependabot
    if: ${{ github.actor != 'dependabot[bot]' && github.actor != 'renovate[bot]' }}
    steps:
      - uses: actions/checkout@v3
        with: # Needed for comparison
          fetch-depth: 0
      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - run: pip install towncrier~=25.8.0
      - name: ":newspaper: Newsfile"
        run: python3 -m towncrier.check --compare-with=origin/main
